services:
  web:
    container_name: chai-server
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      ENV: ${ENV}
      NODE_ENV: ${NODE_ENV}
      CORS_ORIGIN: ${CORS_ORIGIN}
      PORT: ${PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
    ports:
      - '8080:8080'
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
    command: node dist/index.js
