services:
  web:
    container_name: chai-web
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      POSTGRES_HOST: postgres
    ports:
      - '8080:8080'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev
