name: chai

services:
  db:
    container_name: chai-postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  adminer:
    container_name: chai-postgres-adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - ${POSTGRES_ADMIN_PORT}:8080
    networks:
      - internal

volumes:
  pgdata:

networks:
  # everything that is *only* on "internal network" cannot talk to WAN
  internal:
    external: false
  # add this network to a container to make it talk to the rest of the world
  # frontend:
  #   external: true
